// API/games.js — GET /api/games
// Returns the full CycloneX games catalogue as JSON.
// Deploy on Vercel as a serverless function.

const GAMES = [
  { id:1,  name:"Subway Surfers",      cat:"action",   emoji:"🏄", color:"#f59e0b", localPath:"/games/id1/index.html" },
  { id:2,  name:"Slope",               cat:"arcade",   emoji:"🔵", color:"#3b82f6", localPath:"/games/id2/index.html" },
  { id:3,  name:"1v1.LOL",             cat:"action",   emoji:"🔫", color:"#ef4444", localPath:"/games/id3/index.html" },
  { id:4,  name:"Run 3",               cat:"arcade",   emoji:"🏃", color:"#8b5cf6", localPath:"/games/id4/index.html" },
  { id:5,  name:"Drift Hunters",       cat:"racing",   emoji:"🚗", color:"#f97316", localPath:"/games/id5/index.html" },
  { id:6,  name:"Krunker",             cat:"action",   emoji:"🎯", color:"#ef4444", localPath:"/games/id6/index.html" },
  { id:7,  name:"Shell Shockers",      cat:"action",   emoji:"🥚", color:"#fbbf24", localPath:"/games/id7/index.html" },
  { id:8,  name:"Paper.io 2",          cat:"action",   emoji:"📄", color:"#3b82f6", localPath:"/games/id8/index.html" },
  { id:9,  name:"Agar.io",             cat:"action",   emoji:"🔵", color:"#22c55e", localPath:"/games/id9/index.html" },
  { id:10, name:"Slither.io",          cat:"action",   emoji:"🐍", color:"#84cc16", localPath:"/games/id10/index.html" },
  { id:11, name:"Bonk.io",             cat:"action",   emoji:"🏀", color:"#f97316", localPath:"/games/id11/index.html" },
  { id:12, name:"Diep.io",             cat:"action",   emoji:"🔫", color:"#6366f1", localPath:"/games/id12/index.html" },
  { id:13, name:"Zombs Royale",        cat:"action",   emoji:"🧟", color:"#6b7280", localPath:"/games/id13/index.html" },
  { id:14, name:"Surviv.io",           cat:"action",   emoji:"💀", color:"#78716c", localPath:"/games/id14/index.html" },
  { id:15, name:"Moomoo.io",           cat:"action",   emoji:"🌾", color:"#a3e635", localPath:"/games/id15/index.html" },
  { id:16, name:"Wings.io",            cat:"action",   emoji:"✈️", color:"#38bdf8", localPath:"/games/id16/index.html" },
  { id:17, name:"Wormate.io",          cat:"action",   emoji:"🪱", color:"#4ade80", localPath:"/games/id17/index.html" },
  { id:18, name:"Narrow.one",          cat:"action",   emoji:"🏹", color:"#92400e", localPath:"/games/id18/index.html" },
  { id:19, name:"Ev.io",               cat:"action",   emoji:"🔫", color:"#6366f1", localPath:"/games/id19/index.html" },
  { id:20, name:"Buildnow.gg",         cat:"action",   emoji:"🔨", color:"#f59e0b", localPath:"/games/id20/index.html" },
  { id:21, name:"Venge.io",            cat:"action",   emoji:"🎯", color:"#dc2626", localPath:"/games/id21/index.html" },
  { id:22, name:"Getaway Shootout",    cat:"action",   emoji:"🏃", color:"#f97316", localPath:"/games/id22/index.html" },
  { id:23, name:"Rooftop Snipers",     cat:"action",   emoji:"🎯", color:"#374151", localPath:"/games/id23/index.html" },
  { id:24, name:"Minecraft Classic",   cat:"action",   emoji:"⛏️", color:"#22c55e", localPath:"/games/id24/index.html" },
  { id:25, name:"Cookie Clicker",      cat:"arcade",   emoji:"🍪", color:"#d97706", localPath:"/games/id25/index.html" },
  { id:26, name:"Geometry Dash Lite",  cat:"arcade",   emoji:"🔷", color:"#6366f1", localPath:"/games/id26/index.html" },
  { id:27, name:"Friday Night Funkin", cat:"arcade",   emoji:"🎵", color:"#ec4899", localPath:"/games/id27/index.html" },
  { id:28, name:"Crossy Road",         cat:"arcade",   emoji:"🐔", color:"#fbbf24", localPath:"/games/id28/index.html" },
  { id:29, name:"Vex 7",               cat:"arcade",   emoji:"🏃", color:"#ef4444", localPath:"/games/id29/index.html" },
  { id:30, name:"Drift Boss",          cat:"arcade",   emoji:"🚗", color:"#0ea5e9", localPath:"/games/id30/index.html" },
  { id:31, name:"Stickman Hook",       cat:"arcade",   emoji:"🕸️", color:"#374151", localPath:"/games/id31/index.html" },
  { id:32, name:"Moto X3M",            cat:"arcade",   emoji:"🏍️", color:"#f97316", localPath:"/games/id32/index.html" },
  { id:33, name:"Fireboy & Watergirl", cat:"arcade",   emoji:"🔥", color:"#ef4444", localPath:"/games/id33/index.html" },
  { id:34, name:"Tunnel Rush",         cat:"arcade",   emoji:"🌀", color:"#a855f7", localPath:"/games/id34/index.html" },
  { id:35, name:"Red Ball 4",          cat:"arcade",   emoji:"🔴", color:"#ef4444", localPath:"/games/id35/index.html" },
  { id:36, name:"Temple Run 2",        cat:"arcade",   emoji:"🏛️", color:"#78350f", localPath:"/games/id36/index.html" },
  { id:37, name:"Jetpack Joyride",     cat:"arcade",   emoji:"🚀", color:"#6366f1", localPath:"/games/id37/index.html" },
  { id:38, name:"Hole.io",             cat:"arcade",   emoji:"⚫", color:"#374151", localPath:"/games/id38/index.html" },
  { id:39, name:"Space is Key",        cat:"arcade",   emoji:"🚀", color:"#1e40af", localPath:"/games/id39/index.html" },
  { id:40, name:"Happy Wheels",        cat:"arcade",   emoji:"🤪", color:"#ef4444", localPath:"/games/id40/index.html" },
  { id:41, name:"2048",                cat:"arcade",   emoji:"🔢", color:"#f59563", builtin:"g2048" },
  { id:42, name:"Snake",               cat:"arcade",   emoji:"🐍", color:"#4caf50", builtin:"gsnake" },
  { id:43, name:"Pong",                cat:"arcade",   emoji:"🏓", color:"#00bcd4", builtin:"gpong" },
  { id:44, name:"Tetris",              cat:"puzzle",   emoji:"🟦", color:"#2196f3", builtin:"gtetris" },
  { id:45, name:"Wordle",              cat:"puzzle",   emoji:"🟩", color:"#6aaa64", builtin:"gwordle" },
  { id:46, name:"Minesweeper",         cat:"puzzle",   emoji:"💣", color:"#607d8b", builtin:"gmine" },
  { id:47, name:"Memory Match",        cat:"puzzle",   emoji:"🃏", color:"#673ab7", builtin:"gmemory" },
  { id:48, name:"Simon Says",          cat:"puzzle",   emoji:"🔴", color:"#ff5722", builtin:"gsimon" },
  { id:49, name:"Breakout",            cat:"puzzle",   emoji:"🧱", color:"#e91e63", builtin:"gbreakout" },
  { id:50, name:"Asteroids",           cat:"puzzle",   emoji:"🚀", color:"#9c27b0", builtin:"gasteroids" },
  { id:51, name:"Cut the Rope",        cat:"puzzle",   emoji:"🐸", color:"#22c55e", localPath:"/games/id51/index.html" },
  { id:52, name:"Bob The Robber",      cat:"puzzle",   emoji:"🦹", color:"#374151", localPath:"/games/id52/index.html" },
  { id:53, name:"Mahjong",             cat:"puzzle",   emoji:"🀄", color:"#dc2626", localPath:"/games/id53/index.html" },
  { id:54, name:"Sudoku",              cat:"puzzle",   emoji:"🔢", color:"#0284c7", localPath:"/games/id54/index.html" },
  { id:55, name:"Solitaire",           cat:"puzzle",   emoji:"🃏", color:"#059669", localPath:"/games/id55/index.html" },
  { id:56, name:"Bloxorz",             cat:"puzzle",   emoji:"📦", color:"#0891b2", localPath:"/games/id56/index.html" },
  { id:57, name:"Snail Bob",           cat:"puzzle",   emoji:"🐌", color:"#84cc16", localPath:"/games/id57/index.html" },
  { id:58, name:"Gold Miner",          cat:"puzzle",   emoji:"⛏️", color:"#ca8a04", localPath:"/games/id58/index.html" },
  { id:59, name:"Cubes 2048",          cat:"puzzle",   emoji:"🎲", color:"#7c3aed", localPath:"/games/id59/index.html" },
  { id:60, name:"Smash Karts",         cat:"racing",   emoji:"🏎️", color:"#f97316", localPath:"/games/id60/index.html" },
  { id:61, name:"Moto X3M Pool Party", cat:"racing",   emoji:"🏊", color:"#06b6d4", localPath:"/games/id61/index.html" },
  { id:62, name:"Road Fury",           cat:"racing",   emoji:"🚗", color:"#ef4444", localPath:"/games/id62/index.html" },
  { id:63, name:"Traffic Jam 3D",      cat:"racing",   emoji:"🚦", color:"#f97316", localPath:"/games/id63/index.html" },
  { id:64, name:"Burnout Drift",       cat:"racing",   emoji:"💨", color:"#78716c", localPath:"/games/id64/index.html" },
  { id:65, name:"Racing Limits",       cat:"racing",   emoji:"🏎️", color:"#0284c7", localPath:"/games/id65/index.html" },
  { id:66, name:"Highway Racer 3D",    cat:"racing",   emoji:"🛣️", color:"#374151", localPath:"/games/id66/index.html" },
  { id:67, name:"Crazy Cars",          cat:"racing",   emoji:"🤪", color:"#a855f7", localPath:"/games/id67/index.html" },
  { id:68, name:"Basketball Stars",    cat:"sports",   emoji:"🏀", color:"#f97316", localPath:"/games/id68/index.html" },
  { id:69, name:"Soccer Random",       cat:"sports",   emoji:"⚽", color:"#22c55e", localPath:"/games/id69/index.html" },
  { id:70, name:"Boxing Random",       cat:"sports",   emoji:"🥊", color:"#ef4444", localPath:"/games/id70/index.html" },
  { id:71, name:"Football Legends",    cat:"sports",   emoji:"🏈", color:"#7c3aed", localPath:"/games/id71/index.html" },
  { id:72, name:"Tennis Legends",      cat:"sports",   emoji:"🎾", color:"#84cc16", localPath:"/games/id72/index.html" },
  { id:73, name:"Golf Battle",         cat:"sports",   emoji:"⛳", color:"#059669", localPath:"/games/id73/index.html" },
  { id:74, name:"Penalty Shooters",    cat:"sports",   emoji:"🥅", color:"#0284c7", localPath:"/games/id74/index.html" },
  { id:75, name:"Stickman Soccer",     cat:"sports",   emoji:"⚽", color:"#16a34a", localPath:"/games/id75/index.html" },
  { id:76, name:"Bloons TD 5",         cat:"strategy", emoji:"🎈", color:"#ef4444", localPath:"/games/id76/index.html" },
  { id:77, name:"Kingdom Rush",        cat:"strategy", emoji:"🏰", color:"#92400e", localPath:"/games/id77/index.html" },
  { id:78, name:"Chess",               cat:"strategy", emoji:"♟️", color:"#374151", localPath:"/games/id78/index.html" },
  { id:79, name:"Checkers",            cat:"strategy", emoji:"🔴", color:"#dc2626", localPath:"/games/id79/index.html" },
  { id:80, name:"Tic Tac Toe",         cat:"strategy", emoji:"⭕", color:"#0284c7", localPath:"/games/id80/index.html" },
  { id:81, name:"Backgammon",          cat:"strategy", emoji:"🎲", color:"#b45309", localPath:"/games/id81/index.html" },
  { id:82, name:"Battleship",          cat:"strategy", emoji:"🚢", color:"#1e40af", localPath:"/games/id82/index.html" },
  { id:83, name:"Pandemic",            cat:"strategy", emoji:"🦠", color:"#dc2626", localPath:"/games/id83/index.html" },
  { id:84, name:"Flappy Bird",         cat:"builtin",  emoji:"🐦", color:"#fde68a", builtin:"gflappy" },
  { id:85, name:"Dino Run",            cat:"builtin",  emoji:"🦕", color:"#78716c", builtin:"gdino" }
];

export default function handler(req, res) {
  const { cat, q } = req.query;
  let games = GAMES;
  if (cat && cat !== "all") games = games.filter(g => g.cat === cat);
  if (q) games = games.filter(g => g.name.toLowerCase().includes(q.toLowerCase()));
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Cache-Control", "public, s-maxage=3600");
  res.json({ count: games.length, games });
}
